inherit_from: https://raw.githubusercontent.com/discourse/discourse/master/.rubocop.yml

AllCops:
  DisabledByDefault: true
  Exclude:
    - 'db/schema.rb'
    - 'bundle/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Bundler/OrderedGems:
  Enabled: true

Layout/EmptyLines:
  Enabled: true
